apiVersion: batch/v1
kind: Job
metadata:
  name: nlp-ticket-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline
        image: ton-repo/it-support-nlp:latest
        volumeMounts:
        - name: data-storage
          mountPath: /app/data
      restartPolicy: OnFailure
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: nlp-pvc